apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: moesora
spec:
  displayName: Moesora
  author:
    name: Hoshi
    website: https://www.moesora.cn/
  description: As lovely as sora! A dreamy anime-style theme for Halo 2.x
  logo: /themes/moesora/assets/dist/logo.svg
  homepage: https://github.com/7l4i8y1a4n3g8-7l4i8y1a4n3g8-1438-9748/moesora
  repo: https://github.com/7l4i8y1a4n3g8-7l4i8y1a4n3g8-1438-9748/moesora.git
  issues: https://github.com/7l4i8y1a4n3g8-7l4i8y1a4n3g8-1438-9748/moesora/issues
  version: 1.2.0
  requires: '>=2.14.0'
  settingName: moesora-settings
  configMapName: moesora-configmap
  customTemplates:
    page:
    - name: Wish Wall
      description: 'Interactive sticky note message wall for visitors (requires comment
        widget, recommended slug: wishes)'
      screenshot: ''
      file: page_wishes.html
  license:
  - name: MIT
    url: https://github.com/7l4i8y1a4n3g8-7l4i8y1a4n3g8-1438-9748/moesora/blob/master/LICENSE
